# Sample Config File
# 1. Copy this file in the root folder and rename if `_config.xml`.
# 2. From terminal, in the root folder, run `bundle init` to create the Gemfile.
# 3. Paste `gem "jekyll"` to the generated Gemfile in the root folder.
# 4. From terminal, run `bundle exec jekyll serve` to bundle and start server.
# 5. Go to `http://localhost:4000` to see your bundle.

title: Title
description: Description

# Build settings
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

sass:
  sass_dir: _scss
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - bower_components
  - webpack.config.js
  - package.json
